version: '2'

services:
  cinema-catalog-service:
    container_name: "${SERVICE_CONTAINER_NAME}"
    build: .
    command: npm start
    ports:
      - "${MOVIES_SERVICE_EXPOSED_PORT}:3000"
    env_file: .env
    links:
      - mongodb:mongo
    depends_on:
      - mongodb

  mongodb:
    container_name: "${MONGO_CONTAINER_NAME}"
    build: ./mongo/
    ports:
      - "${MONGO_EXPOSED_PORT}:27017"
    env_file: .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
