version: '2'

services:
  movies-service:
    container_name: movies_service
    build: .
    command: npm start
    ports:
      - "${MOVIES_SERVICE_EXPOSED_PORT}:3000"
    env_file: .env
    links:
      - mongodb:mongo
    depends_on:
      - mongodb

  mongodb:
    container_name: monogo_container
    build: ./mongo/
    ports:
      - "${MONGO_EXPOSED_PORT}:27017"
    env_file: .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
